using System;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.Rendering;using UnityEngine.Rendering.HighDefinition;using Unity.Cinemachine;
public static class ConfigureVictory {
 public static string Run(){if(EditorApplication.isPlaying||EditorUtility.scriptCompilationFailed)throw new Exception("Compiled Edit Mode required");
 const string pp="Assets/Mock/ScriptableObjects/VictoryMonochrome.asset";var profile=AssetDatabase.LoadAssetAtPath<VolumeProfile>(pp);if(profile==null){profile=ScriptableObject.CreateInstance<VolumeProfile>();AssetDatabase.CreateAsset(profile,pp);}if(!profile.TryGet<ColorAdjustments>(out var color)){color=profile.Add<ColorAdjustments>(false);AssetDatabase.AddObjectToAsset(color,profile);}color.saturation.Override(-100);EditorUtility.SetDirty(profile);EditorUtility.SetDirty(color);
 const string path="Assets/Mock/Prefabs/Manager/CameraManager.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{
 var contrast=root.GetComponent<VictoryContrast>()??root.AddComponent<VictoryContrast>();var go=new GameObject("Victory Monochrome Volume");go.transform.SetParent(root.transform,false);var v=go.AddComponent<Volume>();v.isGlobal=true;v.priority=110;v.weight=0;v.sharedProfile=profile;var so=new SerializedObject(contrast);so.FindProperty("_volume").objectReferenceValue=v;so.FindProperty("_enter").floatValue=.04f;so.FindProperty("_hold").floatValue=2.08f;so.FindProperty("_restore").floatValue=.45f;so.ApplyModifiedPropertiesWithoutUndo();
 go=new GameObject("Victory Camera");go.transform.SetParent(root.transform,false);var camera=go.AddComponent<CinemachineCamera>();camera.Priority=-100;camera.enabled=false;
 var rig=root.GetComponent<VictoryCameraRig>()??root.AddComponent<VictoryCameraRig>();so=new SerializedObject(rig);so.FindProperty("_camera").objectReferenceValue=camera;so.ApplyModifiedPropertiesWithoutUndo();PrefabUtility.SaveAsPrefabAsset(root,path,out bool saved);if(!saved)throw new Exception("Camera save failed");
 }finally{PrefabUtility.UnloadPrefabContents(root);}
 var scene=EditorSceneManager.OpenScene("Assets/Mock/Scenes/GameScene.unity",OpenSceneMode.Additive);try{foreach(var r in scene.GetRootGameObjects()){
 foreach(var manager in r.GetComponentsInChildren<FinalBlowManager>(true)){var so=new SerializedObject(manager);so.FindProperty("_textDelay").floatValue=2.12f;so.FindProperty("_finalBlowTextFadeIn").floatValue=.22f;so.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(manager);}
 foreach(var p in r.GetComponentsInChildren<FinalBlowPresentation>(true)){var so=new SerializedObject(p);so.FindProperty("_textStartScale").floatValue=.9f;so.FindProperty("_textOvershootScale").floatValue=1.025f;so.FindProperty("_textRiseFraction").floatValue=.55f;so.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(p);}}
 EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("GameScene save failed");}finally{EditorSceneManager.CloseScene(scene,true);}AssetDatabase.SaveAssets();return "Saved victory Volume/Profile/virtual camera prefab and GameScene. Text 2.12s/.22s; monochrome .04/2.08/.45; scene fade remains 3.1s. Just Avoid settings untouched.";
 }
}
