using System;using System.Linq;using System.IO;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;
public static class InspectSerializedFields {
 [Serializable] public class Entry {public string path,owner,name,type,tooltip;}
 [Serializable] public class Entries {public List<Entry> fields=new List<Entry>();}
 static void Collect(Type t,string path,Entries e){if(typeof(UnityEngine.Object).IsAssignableFrom(t)||t.IsDefined(typeof(SerializableAttribute),false))foreach(var f in t.GetFields(BindingFlags.DeclaredOnly|BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)){if(f.IsStatic||f.IsInitOnly||f.IsDefined(typeof(NonSerializedAttribute),false)||(!f.IsPublic&&!f.IsDefined(typeof(SerializeField),false)&&!f.IsDefined(typeof(SerializeReference),false)))continue;var tooltip=f.GetCustomAttribute<TooltipAttribute>();e.fields.Add(new Entry{path=path,owner=t.Name,name=f.Name,type=f.FieldType.Name,tooltip=tooltip?.tooltip??""});}foreach(var n in t.GetNestedTypes(BindingFlags.Public|BindingFlags.NonPublic))Collect(n,path,e);}
 public static string Run(){var e=new Entries();foreach(var guid in AssetDatabase.FindAssets("t:MonoScript",new[]{"Assets/Mock/Scripts"})){var path=AssetDatabase.GUIDToAssetPath(guid);var script=AssetDatabase.LoadAssetAtPath<MonoScript>(path);var t=script.GetClass();if(t!=null)Collect(t,path,e);} // Serializable data classes may share a file with a different main type.
 var seen=new HashSet<string>(e.fields.Select(x=>x.owner+"."+x.name));var paths=AssetDatabase.FindAssets("t:MonoScript",new[]{"Assets/Mock/Scripts"}).Select(AssetDatabase.GUIDToAssetPath).ToArray();foreach(var t in typeof(PlayerController).Assembly.GetTypes().Where(t=>t.IsDefined(typeof(SerializableAttribute),false)&&!t.IsNested)){var path=paths.FirstOrDefault(p=>System.Text.RegularExpressions.Regex.IsMatch(File.ReadAllText(p),@"\b(class|struct)\s+"+t.Name+@"\b"));if(path==null)continue;var extra=new Entries();Collect(t,path,extra);foreach(var x in extra.fields)if(seen.Add(x.owner+"."+x.name))e.fields.Add(x);}
 File.WriteAllText("AgentScripts/SerializedFields.json",Newtonsoft.Json.JsonConvert.SerializeObject(e,Newtonsoft.Json.Formatting.Indented));return "Serialized fields="+e.fields.Count+", existing tooltips="+e.fields.Count(x=>!string.IsNullOrEmpty(x.tooltip));}
}
