import json
from pathlib import Path
p=Path('AgentScripts/summary_catalog.json');c=json.loads(p.read_text(encoding='utf-8'))
rows='''
BossBarSilhouette.ModifyMesh=通常の四角形Imageを指定輪郭の三角形群へ置き換え、バーの装飾外側を描画しない。
BossBarSilhouette.Add=輪郭の正規化座標から元Imageの位置とUVを補間し、描画頂点を追加する。
DamageTrailGauge.SetNormalized=現在ゲージを即時更新する。減少時だけ遅延追従を予約し、回復・初期化時は遅延ゲージも一致させる。
DamageTrailGauge.Update=TimeScaleに依存せず遅延ゲージの追従を進める。
DamageTrailGauge.Tick=待機時間が終わった遅延ゲージを現在値へ指定速度で近づける。
DamageTrailGauge.OnDisable=遅延表示を現在値へ揃えて待機時刻を解除する。
EquipmentOptionSelection.OnSelect=方向入力で選択された有効なToggleをオンにして装備選択へ反映する。
FinalBlowPresentation.Begin=元の文字・HUD状態を保存し、Flash・黒帯・討伐表示の実時間タイムラインを開始する。
FinalBlowPresentation.Update=勝利UIが進行中の間だけ、開始からの実経過時間で表示を更新する。
FinalBlowPresentation.RenderAt=指定経過秒でFlash、HUD非表示、黒帯と討伐文字の素早い出現・Scaleの落ち着きを反映する。
FinalBlowPresentation.SetLetterbox=画面高の比率を使って上下黒帯のAnchorを移動し、解像度に依存せず出現させる。
FinalBlowPresentation.ResetPresentation=Flashと黒帯を解除し、保存したHUD・文字の色・Scale・有効状態を復元する。
FinalBlowPresentation.OnDisable=勝利UIを解除して停止前のHUDと文字状態を復元する。
FinalBlowPresentation.OnDestroy=勝利UIが保持した一時表示を解除して元の状態へ戻す。
PlayerHUDPresenter.UpdateHp=現在HPを最大HPで正規化してViewへ渡す。最大HPが無効ならゼロ表示にする。
PlayerHUDView.SetHpNormalized=現在HPを即反映し、減少時は赤いダメージ履歴を遅延追従させる。回復時は両表示を揃える。
PlayerHUDView.Update=HPの遅延表示を実時間で進め、HitStop中もUIの追従を維持する。
PlayerHUDView.TickDamageTrail=減少後の待機時間を過ぎた赤いゲージを現在HPへ指定速度で近づける。
PlayerHUDView.SetSkillNormalized=スキルゲージ値を0から1へ制限してImageの充填量へ反映する。
PlayerHUDView.OnDisable=HPの遅延表示を現在値へ揃え、待機時刻をリセットする。
RunHUD.SetPresentationVisibility=勝利演出などの表示所有者から、通常のラン情報を表示してよいか切り替える。
RunHUD.Init=共有Faderを接続し、配置済みのラン情報表示を一度だけ初期化する。
RunHUD.LateUpdate=ランの残機・相手・結果などを表示し、演出による非表示指定を優先する。
RunHUD.SetLabel=参照があり文字列が変わった場合だけTMPテキストを更新する。
RunSetupUI.Init=装備Toggleと開始Buttonの通知を一度だけ接続し、初期状態では設定画面を隠す。
RunSetupUI.Open=保存中の名前・装備・前回勝者を表示し、操作可能な設定画面とUI選択を開始する。
RunSetupUI.RefreshDescriptions=現在選択中の攻撃・防御装備の効果説明を更新する。
RunSetupUI.Confirm=画面を開いた同フレームの入力を除外し、選択内容でランを開始してTitleの遷移を要求する。
RunSetupUI.SetVisible=設定パネルの不透明度と入力・Raycast受付をまとめて切り替える。
TitleText.Init=TitleとFaderを接続し、有効な文字表示なら実時間の点滅を開始する。
TitleText.OnEnable=初期化済みのTitle文字に点滅Tweenを再開する。
TitleText.StartPulse=文字のFadeと待機を繰り返すTweenを実時間更新で組み立てる。
TitleText.OnDisable=所有する点滅Tweenを停止して参照を解除する。
TitleText.OnStartButton=多重遷移を防ぎ、TitleManagerの設定画面または既存のゲーム開始処理を要求する。
TitleText.StartGame=共有FaderでGameSceneへ遷移し、成功・中断にかかわらず遷移中フラグを解除する。
GameplayRules.Regen=HP割合に応じて低HP時と満HP時のゲージ回復倍率を補間する。|0以上のゲージ自然回復倍率。
GameplayRules.SelfCost=HP割合に応じて低HP時と満HP時の自傷消費倍率を補間する。|0以上の自傷コスト倍率。
GameplayRules.AvoidWindow=HP割合に応じてジャスト回避受付時間の倍率を補間する。|0以上の回避受付倍率。
RunSession.AttackDescription=選択した攻撃装備の倍率や低HP効果を現在の調整値から説明文へ変換する。|攻撃装備の日本語説明。
RunSession.DefenseDescription=選択した防御装備の被ダメージ・幽体化コスト・回復効果を説明文へ変換する。|防御装備の日本語説明。
RunSession.Reset=新しい実行セッション開始時にランの状態・前回相手・結果・保存エラーを消去する。
RunSession.CleanName=名前から制御文字とタグ記号を除き、長さを制限して空の場合は既定名を使用する。|表示と保存に使用する整形済みの名前。
RunSession.ReadChampion=PlayerPrefsの勝者データを読み込み、欠損や不正な保存値の場合は相手なしとして扱う。|検証済みの勝者データ。保存がない・不正な場合はnull。
RunSession.Begin=名前と装備選択を検証して残機・相手・開始時刻を初期化し、新しいランを有効にする。
RunSession.EnsureRun=ラン未開始の場合だけ、保持している名前と装備で開始する。
RunSession.ConsumeLife=有効なランの残機を一つ減らし、復活可能かを返す。|消費後に残機があり復活可能ならtrue。
RunSession.Complete=有効なランを一度だけ完了し、勝利時は名前・装備・実所要時間を次回相手として保存する。
RunSession.DamageMultiplier=攻撃装備と現在HP割合からPlayerの与ダメージ倍率を求める。|現在の装備・HPに対応する与ダメージ倍率。
RunSession.EnemyDamage=前回勝者の攻撃装備とEnemyのHP割合から継承された攻撃倍率を求める。|Enemyの与ダメージ倍率。継承相手がなければ1。
StatusEffectInstance.StatusEffectInstance=効果定義と付与元を保持し、残り時間・一段階のスタックと未生成VFXを初期化する。
StatusEffectManager.Init=AnimatorとAgentを取得し、基準移動速度と合成用の速度制御を一度だけ接続する。
StatusEffectManager.Update=効果の残り時間を進め、期限切れのVFXを除去して倍率の変更を再計算する。
StatusEffectManager.ApplyStatusEffect=同じIDの効果を定義の更新・置換・加算方式で合成し、新規の場合はVFXを生成して倍率を反映する。
StatusEffectManager.OnDisable=全効果とVFXを解除し、Animator倍率とAgent移動速度を基準へ戻す。
'''
for row in rows.strip().splitlines():
 key,value=row.split('=',1);file,method=key.split('.',1);c.setdefault(file,{})[method]=value
p.write_text(json.dumps(c,ensure_ascii=False,indent=2),encoding='utf-8')
