using System;using System.IO;using System.Reflection;using System.Text;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.Rendering;using UnityEngine.Rendering.HighDefinition;using Unity.Cinemachine;using TMPro;
public static class ValidateVictory {
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static void Check(bool v,string message){if(!v)throw new Exception(message);}
 static void Near(float a,float b,string message){Check(Mathf.Abs(a-b)<.002f,message+" "+a+" != "+b);}
 static void Set(object o,string field,object v){o.GetType().GetField(field,flags).SetValue(o,v);}
 public static string Run(){Check(!EditorApplication.isPlaying&&!EditorUtility.scriptCompilationFailed,"Compiled Edit Mode required");var b=new StringBuilder();
 var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Mock/Prefabs/Manager/CameraManager.prefab");var victory=prefab.GetComponent<VictoryContrast>();var vso=new SerializedObject(victory);var vol=(Volume)vso.FindProperty("_volume").objectReferenceValue;Check(vol!=null&&vol.isGlobal&&vol.priority==110&&vol.weight==0,"Victory dedicated volume");Check(vol.sharedProfile.TryGet<ColorAdjustments>(out var color)&&color.saturation.overrideState&&color.saturation.value==-100,"Victory monochrome profile");Near(vso.FindProperty("_enter").floatValue,.04f,"Enter");Near(vso.FindProperty("_hold").floatValue,2.08f,"Hold");Near(vso.FindProperty("_restore").floatValue,.45f,"Restore");var jso=new SerializedObject(prefab.GetComponent<JustAvoidContrast>());Near(jso.FindProperty("_enter").floatValue,.02f,"Just Avoid enter protected");Near(jso.FindProperty("_hold").floatValue,.08f,"Just Avoid hold protected");Near(jso.FindProperty("_restore").floatValue,.20f,"Just Avoid restore protected");Check(((Volume)jso.FindProperty("_volume").objectReferenceValue).sharedProfile!=vol.sharedProfile,"Independent profiles");
 var scene=EditorSceneManager.OpenPreviewScene("Assets/Mock/Scenes/GameScene.unity");int managers=0;
 try{foreach(var root in scene.GetRootGameObjects())foreach(var manager in root.GetComponentsInChildren<FinalBlowManager>(true)){
 managers++;var so=new SerializedObject(manager);Near(so.FindProperty("_phase1HitStop").floatValue,.20f,"HitStop protected");Near(so.FindProperty("_whiteFlashDuration").floatValue,.10f,"Flash protected");Near(so.FindProperty("_sheathingDelay").floatValue,.80f,"Sheathing start protected");Near(so.FindProperty("_textDelay").floatValue,2.12f,"Text synchronized");Near(so.FindProperty("_phase2Duration").floatValue,2.30f,"Total duration protected");Check(so.FindProperty("_cameraFeedback").objectReferenceValue!=null,"Camera reference");
 var p=(FinalBlowPresentation)so.FindProperty("_presentation").objectReferenceValue;var text=(TMP_Text)so.FindProperty("_finalBlowText").objectReferenceValue;Check(p!=null&&text!=null,"Presentation references");Color oldColor=text.color;Vector3 oldScale=text.transform.localScale;bool oldActive=text.gameObject.activeSelf;
 p.Begin(text,.10f,2.12f,.22f);p.RenderAt(2.11f);Check(!text.gameObject.activeSelf,"No premature text");p.RenderAt(2.241f);Near(text.alpha,oldColor.a,"Fast reveal");Near(text.transform.localScale.x/oldScale.x,1.025f,"Small overshoot");p.RenderAt(2.34f);Near(text.transform.localScale.x,oldScale.x,"Text settles");p.ResetPresentation();Near(text.color.a,oldColor.a,"Text alpha restored");Check(text.transform.localScale==oldScale&&text.gameObject.activeSelf==oldActive,"Text state restored");}
 }finally{EditorSceneManager.ClosePreviewScene(scene);}Check(managers==1,"One FinalBlow owner");b.AppendLine("PASS saved scene timing, text reveal/settle/reset, independent profiles and protected Just Avoid/HitStop settings.");
 var g=(GameObject)PrefabUtility.InstantiatePrefab(prefab);var outputGo=new GameObject("Victory test camera",typeof(Camera),typeof(CinemachineBrain));var player=new GameObject("Victory test player");try{
 var c=g.GetComponent<VictoryContrast>();var v=g.GetComponentsInChildren<Volume>(true);var runtimeVol=(Volume)new SerializedObject(c).FindProperty("_volume").objectReferenceValue;var env=new JustAvoidEnvelope();env.Begin(0);Set(c,"_envelope",env);c.RenderAt(.04f);Near(runtimeVol.weight,1,"Mono peak");c.RenderAt(2.12f);Near(runtimeVol.weight,1,"Mono until sheath event");c.RenderAt(2.345f);Near(runtimeVol.weight,.5f,"Smooth recovery");c.RenderAt(2.58f);Near(runtimeVol.weight,0,"Auto recovery");env.Begin(0);Set(c,"_envelope",env);c.RenderAt(.1f);c.Cancel();Near(runtimeVol.weight,0,"Cancel recovery");
 player.transform.position=new Vector3(10000,10000,10000);outputGo.transform.SetPositionAndRotation(player.transform.position+new Vector3(0,1.5f,-3),Quaternion.identity);var brain=outputGo.GetComponent<CinemachineBrain>();brain.enabled=false;
 var rig=g.GetComponent<VictoryCameraRig>();rig.Init(player.transform,outputGo.GetComponent<Camera>());var start=outputGo.transform.position;var rotation=outputGo.transform.rotation;rig.Begin(.18f);Check(brain.enabled,"Temporarily enable lock-on Brain");float started=(float)typeof(VictoryCameraRig).GetField("_started",flags).GetValue(rig);rig.Tick(started+.55f);var vc=(CinemachineCamera)new SerializedObject(rig).FindProperty("_camera").objectReferenceValue;Check(vc.enabled,"Victory camera active");Check(vc.transform.position.x>player.transform.position.x+2,"Oblique side view");Vector3 aim=player.transform.position+Vector3.up*1.15f+player.transform.right*.18f;Check(Vector3.Dot(vc.transform.forward,(aim-vc.transform.position).normalized)>.999f,"Upper body target");Near(outputGo.GetComponent<Camera>().fieldOfView,60,"Output lens untouched before Brain evaluation");brain.ManualUpdate();Check(Vector3.Distance(outputGo.transform.position,vc.transform.position)<.01f,"Brain applies victory pose");rig.Stop();Check(!brain.enabled&&!vc.enabled,"Camera ownership restored");Check(outputGo.transform.position==start&&outputGo.transform.rotation==rotation,"Manual lock-on pose restored");
 b.AppendLine("PASS monochrome clock/auto recovery/cancel; native Cinemachine override lifecycle, side pose, upper-body aim, disabled Brain restoration.");
 }finally{UnityEngine.Object.DestroyImmediate(g);UnityEngine.Object.DestroyImmediate(outputGo);UnityEngine.Object.DestroyImmediate(player);}
 AssetDatabase.SaveAssets();b.AppendLine("Compile errors=0. Native saved settings re-read. Play Mode not entered; runtime input/render/audio/AI and actual scene transition unverified.");File.WriteAllText("AgentScripts/VictoryTests.txt",b.ToString());return b.ToString();
 }
}
